spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/clothingbrand
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        types.print.banner: false
        format_sql: true
    show-sql: true

jwt:
  secret: ${JWT_SECRET:VfbJTwagLbTybf0Wq28UZd8GD1PfbwCg6gZlMblkyeE=}
  expiration: ${JWT_EXPIRATION:3600000}
  refreshExpiration: ${JWT_REFRESH_EXPIRATION:604800000}

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.core.env: TRACE
